movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'
urlpatterns = [

    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields = ['name', 'desc', 'year', 'img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie

    }
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['image']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')


def update(request, id):
    movie =Movie.objects.get(id=id)
    form= MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie':movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" class="text-center" enctype="multipart/form-data">
  {% csrf_token %}
  <br>
  <input type="text" placeholder="name" name="name"><br><br>
  <input type="text" placeholder="description" name="desc"><br><br>
  <input type="text" placeholder="year" name="year"><br><br>
  <input type="file" name="image"><br><br>
  <input class="btn btn-primary" type="submit">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MovieStore</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Movie Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
      <a class="nav-link" href="{% url 'movieapp:add_movie' %}">Add Movie</a>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post" class="form m-3">
  {% csrf_token %}
  Are you sure, you want to delete this movie?
  <br>
  <input class="btn btn-danger" type="submit">
</form>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row text-center">
        <div class="col-md-6 col-sm-12 col-lg-6">
            <h2 class="m-2">{{movie.name}}({{movie.year}})</h2>
            <img class="img-fluid m-2" src="{{movie.img.url}}" width="350">

        </div>
        <div class="col-md-6 col-sm-12 col-lg-6">
            <p class="mt-5">{{movie.desc}}</p>
            <br>
            <a class="btn btn-primary" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}

  <input class="btn btn-primary" type="submit">
</form>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-sm-12 col-md-4 col-lg-4 mt-3">
            <div class="card" style="width: auto;">
            <img src="{{i.img.url}}" class="card-img-top" alt="..." width="200" height="350">
            <div class="card-body">
            <h5 class="card-title">{{ i.name }}</h5>
            <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Get details</a>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}